### ISSUE TITLE
Remove privileged: true from beyla sample

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operator-sample#78]
We currently have this securityContext for the beyla daemonset:

https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/blob/b159122a1b3ac396ada5ccc5ac07c2a6545b9790/recipes/beyla/beyla-daemonset.yaml#L40-L42

We should try to reduce privileges in a way that still works on GKE.

Some potentially helpful links:

* It is possible according to https://github.com/grafana/beyla/blob/6cb90b3c6d64b2806a84991eef9125ad99754e85/docs/sources/setup/kubernetes.md#deploy-beyla-unprivileged
* Original upstream attempt: https://github.com/grafana/beyla/issues/91
* Seems like the workarounds don't work in all cases: https://github.com/grafana/beyla/issues/452
* cilium was able to remove their privileged option: https://github.com/cilium/cilium/pull/14446

**Comment by dashpole** [comment]
I was able to remove `privileged: true` in https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/pull/80.  I tried additionally removing the SYS_ADMIN capability as well, but that resulted in this error: 

```
time=2024-02-20T19:52:30.855Z level=ERROR msg="Beyla couldn't find target process" error="couldn't start Process Finder: can't instantiate discovery.ProcessFinder pipeline: instantiating terminal instance \"TraceAttacher\": can't mount BPF filesystem: operation not permitted"
```

That was when I ran with:

```yaml
            capabilities:
              add:
                - all
              drop:
                - SYS_ADMIN
```

That would seem to imply that even with all other capabilities, beyla can't mount the BPF filesystem without SYS_ADMIN

**Comment by dashpole** [comment]
I also tried to work around this limitation by having a privileged init container mount the BPF filesystem, similar to https://github.com/cilium/cilium/pull/14446/files#diff-264b5e646aa5ad3db682a4a0a9cd4b4cbbae238d88b033d340e901060c89394aR447, but I still got the same error.

```yaml
       initContainers:
         # Mount the bpf fs if it is not mounted. We will perform this task
         # from a privileged container because the mount propagation bidirectional
         # only works from privileged containers.
         - name: mount-bpf-fs
           image: grafana/beyla:1.2.0
           args:
           - 'mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpf /sys/fs/bpf'
           command:
           - /bin/bash
           - -c
           - --
           securityContext:
             privileged: true
           volumeMounts:
           - name: bpffs
             mountPath: /sys/fs/bpf
             mountPropagation: Bidirectional
```

I also set the mountPropagation to HostToContainer in the bpffs mount for the main beyla container.

I still got this error:

```
time=2024-02-20T19:46:34.036Z level=ERROR msg="Beyla couldn't find target process" error="couldn't start Process Finder: can't instantiate discovery.ProcessFinder pipeline: instantiating terminal instance \"TraceAttacher\": can't mount BPF filesystem: operation not permitted"
```

**Comment by dashpole** [comment]
I also tried to work around this limitation by having a privileged init container mount the BPF filesystem, similar to https://github.com/cilium/cilium/pull/14446/files#diff-264b5e646aa5ad3db682a4a0a9cd4b4cbbae238d88b033d340e901060c89394aR447, but I still got the same error.

```yaml
       initContainers:
         # Mount the bpf fs if it is not mounted. We will perform this task
         # from a privileged container because the mount propagation bidirectional
         # only works from privileged containers.
         - name: mount-bpf-fs
           image: grafana/beyla:1.2.0
           args:
           - 'mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpf /sys/fs/bpf'
           command:
           - /bin/bash
           - -c
           - --
           securityContext:
             privileged: true
           volumeMounts:
           - name: bpffs
             mountPath: /sys/fs/bpf
             mountPropagation: Bidirectional
```

I also set the mountPropagation to HostToContainer in the bpffs mount for the main beyla container.

I still got this error:

```
time=2024-02-20T19:46:34.036Z level=ERROR msg="Beyla couldn't find target process" error="couldn't start Process Finder: can't instantiate discovery.ProcessFinder pipeline: instantiating terminal instance \"TraceAttacher\": can't mount BPF filesystem: operation not permitted"
```
