### ISSUE TITLE
Recipe for getting HPA external metrics working

### ISSUE THREAD

**Issue by justsomecorporateuser** [GoogleCloudPlatform/opentelemetry-operator-sample#98]
Trying to find a way for solving these needs:

- Ability for developers to see traces
- Ability to get metrics ( which can then be used for alerting)
- Ability to configure HPA with metrics such as request latencies
- Preferably with zero or as little app code changes as possible 

I have experimented with following setup
- Opentelemetry Operator, with Auto-instrumentation and Collector sending metrics and traces to googlecloud exporter
- Custom metrics Stackdriver adapter (New resource model) picking the metrics from Monitoring
- A HPA trying to get external metric ( latency) for scaling

With that setup
- Traces are going fine to Cloud Trace
- Metrics are going fine to Monitoring.  For my Otel- auto-instrumented app,  i can see the workload.googleapis.com/http.server.request.duration  .  It is however of type DISTRIBUTION 

It seems that the last mile causes problems.  Stackdriver adapter can pick only metric types DOUBLE or INT64.   The HPA is then reporting "unable to fetch metrics from external metrics API: Expected metric of type DoubleValue or Int64Value, but received TypedValue: {<nil> 0xc000d44900 <nil> <nil> <nil> [] []}"

Should i rethink my approach to solve the HPA case?  What would be the way to do that? Add googlemanagedprometheus- exporter? If i continue using existing otlp receivers, would i need to do mapping for time series?

Here is my current Collector config:

    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      googlecloud:
        project: my-project
        metric:
        trace:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [googlecloud]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [googlecloud]

**Comment by justsomecorporateuser** [comment]
Got the problem solved by adding reducer to the HPA

```
apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-hpa
  namespace: test
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metric:
        name: workload.googleapis.com|http.server.request.duration
        selector:
          matchLabels:
            metric.labels.service_name: spring-boot-example
            reducer: "REDUCE_PERCENTILE_99"
      target:
        type: AverageValue
        averageValue: "0.2"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-boot-example
```
